import { Copy, Download, Check } from "lucide-react";
import { useState } from "react";
import type { ValidationReport } from "@/lib/mockData";

interface ExportButtonsProps {
  topicName: string;
  topicSlug: string;
  report: ValidationReport;
}

export function ExportButtons({ topicName, topicSlug, report }: ExportButtonsProps) {
  const [copied, setCopied] = useState(false);
  const [downloading, setDownloading] = useState(false);

  const handleCopy = async () => {
    const text = `📊 SIGNAL VALIDATION REPORT
═══════════════════════════
Idea: ${topicName}
Demand Score: ${report.demandScore}/100 — ${report.verdict}
Signals Found: ${report.signals} across ${report.platforms.join(", ")}

TOP QUOTES:
${report.quotes.slice(0, 3).map((q) => `• "${q.text}" — ${q.platform}, ${q.upvotes} upvotes`).join("\n")}

PAIN CATEGORIES:
${report.painCategories.map((c) => `• ${c.label}: ${c.pct}%`).join("\n")}

COMPETITIVE LANDSCAPE:
${report.competitors.direct} direct competitors, ${report.competitors.indirect} indirect
Dominant player: ${report.competitors.dominantPlayer ? "Yes" : "No"}

RECOMMENDATION:
${report.recommendation}

Generated by Signal — findthesignal.ai`;

    await navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = async () => {
    setDownloading(true);
    try {
      const html2canvas = (await import("html2canvas")).default;
      const section = document.getElementById("proof-stack-export");
      if (!section) return;

      const canvas = await html2canvas(section, {
        backgroundColor: "#0a0a0f",
        scale: 2,
        width: 1200,
        height: 800,
        windowWidth: 1200,
      });

      const link = document.createElement("a");
      link.download = `signal-report-${topicSlug}.png`;
      link.href = canvas.toDataURL("image/png");
      link.click();
    } catch (error) {
      console.error("Download failed:", error);
    } finally {
      setDownloading(false);
    }
  };

  return (
    <div className="flex flex-wrap gap-3">
      <button onClick={handleCopy} className="gradient-button flex items-center gap-2">
        {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
        {copied ? "Copied!" : "Copy Report"}
      </button>
      <button
        onClick={handleDownload}
        disabled={downloading}
        className="gradient-button flex items-center gap-2 opacity-90"
      >
        <Download className="w-4 h-4" />
        {downloading ? "Exporting..." : "Download Card"}
      </button>
    </div>
  );
}
