import { Copy, Download, Check, Plus } from "lucide-react";
import { useState } from "react";
import type { ValidationReport } from "@/types";

interface ExportButtonsProps {
  report: ValidationReport;
  onAddToCompare?: () => void;
  isInCompare?: boolean;
}

export function ExportButtons({ report, onAddToCompare, isInCompare }: ExportButtonsProps) {
  const [copied, setCopied] = useState(false);
  const [downloading, setDownloading] = useState(false);

  const handleCopy = async () => {
    const text = `SIGNAL VALIDATION REPORT
Idea: ${report.ideaTitle}
Validation Score: ${report.overallScore}/100 — ${report.verdict}
Founder Signal: ${report.founderSignal.score}/100 — ${report.founderSignal.summary}
Investor Signal: ${report.investorSignal.score}/100 — ${report.investorSignal.summary}

VALIDATION QUADRANT:
- Gut Check: ${report.quadrants.internalQual.score}/100
- Mom Test Signals: ${report.quadrants.externalQual.score}/100
- Buildability: ${report.quadrants.internalQuant.score}/100
- Market Metrics: ${report.quadrants.externalQuant.score}/100

MOM TEST: ${report.momTest.score}/${report.momTest.maxScore} rules passed

TOP QUOTES:
${report.quotes
  .slice(0, 3)
  .map((q) => `"${q.text}" — ${q.platform}, ${q.upvotes} upvotes`)
  .join("\n")}

SHOULD YOU BUILD THIS?
${report.checklist
  .map(
    (c) =>
      `${c.status === "pass" ? "[pass]" : c.status === "warning" ? "[warn]" : "[fail]"} ${c.label}: ${c.detail}`
  )
  .join("\n")}

VERDICT: ${report.checklistVerdict.greenCount}/${report.checklistVerdict.total} green — ${report.checklistVerdict.recommendation}

RECOMMENDATION:
${report.recommendation}

Generated by Signal`;

    await navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = async () => {
    setDownloading(true);
    try {
      const html2canvas = (await import("html2canvas")).default;
      const section = document.getElementById("proof-stack-export");
      if (!section) return;
      const canvas = await html2canvas(section, {
        backgroundColor: "#ffffff",
        scale: 2,
        width: 1200,
        height: 800,
        windowWidth: 1200,
      });
      const link = document.createElement("a");
      link.download = `signal-${report.ideaTitle
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")}.png`;
      link.href = canvas.toDataURL("image/png");
      link.click();
    } catch (error) {
      console.error("Download failed:", error);
    } finally {
      setDownloading(false);
    }
  };

  return (
    <div className="flex flex-wrap gap-2.5">
      <button onClick={handleCopy} className="btn-primary flex items-center gap-2 text-sm">
        {copied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
        {copied ? "Copied" : "Copy report"}
      </button>
      <button
        onClick={handleDownload}
        disabled={downloading}
        className="btn-secondary flex items-center gap-2 text-sm"
      >
        <Download className="w-3.5 h-3.5" />
        {downloading ? "Exporting..." : "Download card"}
      </button>
      {onAddToCompare && (
        <button
          onClick={onAddToCompare}
          disabled={isInCompare}
          className="btn-secondary flex items-center gap-2 text-sm disabled:opacity-30"
        >
          <Plus className="w-3.5 h-3.5" />
          {isInCompare ? "Added" : "Add to compare"}
        </button>
      )}
    </div>
  );
}
