// supabase/functions/generate-pdf/index.ts
import { corsHeaders } from "../_shared/cors.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { PDFDocument, StandardFonts, rgb, PageSizes } from "https://esm.sh/pdf-lib@1.17.1";

const BRAND = {
  dark: rgb(0.07, 0.07, 0.18),
  accent: rgb(0.22, 0.51, 0.96),
  success: rgb(0.13, 0.69, 0.47),
  warn: rgb(0.93, 0.62, 0.12),
  danger: rgb(0.88, 0.24, 0.24),
  gray: rgb(0.55, 0.55, 0.6),
  lightGray: rgb(0.94, 0.94, 0.96),
  text: rgb(0.1, 0.1, 0.15),
  white: rgb(1, 1, 1),
};

function wrapText(text: string, maxChars: number): string[] {
  const words = String(text || "").split(" ");
  const lines: string[] = [];
  let current = "";
  for (const w of words) {
    if ((current + " " + w).trim().length <= maxChars) {
      current = (current + " " + w).trim();
    } else {
      if (current) lines.push(current);
      current = w;
    }
  }
  if (current) lines.push(current);
  return lines.length ? lines : [""];
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });

  try {
    const body = await req.json();
    let report: any;

    if (body.reportId) {
      const supabase = createClient(
        Deno.env.get("SUPABASE_URL")!,
        Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
      );
      const { data, error } = await supabase
        .from("validation_history")
        .select("report")
        .eq("id", body.reportId)
        .single();
      if (error || !data) throw new Error("Report not found");
      report = data.report;
    } else if (body.report) {
      report = body.report;
    } else {
      throw new Error("Missing report or reportId");
    }

    // ── Build PDF ───────────────────────────────────────────────────────────

    const doc = await PDFDocument.create();
    const fontR = await doc.embedFont(StandardFonts.Helvetica);
    const fontB = await doc.embedFont(StandardFonts.HelveticaBold);

    const W = PageSizes.Letter[0]; // 612
    const H = PageSizes.Letter[1]; // 792
    const ML = 50, MR = 50, MT = 50, MB = 40;
    const CW = W - ML - MR; // content width = 512

    let page = doc.addPage(PageSizes.Letter);
    let y = H - MT;

    const newPage = () => {
      drawFooter(page);
      page = doc.addPage(PageSizes.Letter);
      y = H - MT;
    };

    const ensure = (needed: number) => {
      if (y - needed < MB + 20) newPage();
    };

    const drawFooter = (p: typeof page) => {
      p.drawLine({ start: { x: ML, y: MB + 15 }, end: { x: W - MR, y: MB + 15 }, thickness: 0.5, color: BRAND.gray });
      p.drawText("Generated by Signal — AI-Powered Market Intelligence", {
        x: ML, y: MB, size: 8, font: fontR, color: BRAND.gray,
      });
      p.drawText(`signalvalidator.com`, {
        x: W - MR - 80, y: MB, size: 8, font: fontR, color: BRAND.accent,
      });
    };

    const drawSection = (title: string) => {
      ensure(40);
      page.drawRectangle({ x: ML, y: y - 22, width: CW, height: 22, color: BRAND.dark });
      page.drawText(title.toUpperCase(), {
        x: ML + 10, y: y - 16, size: 9, font: fontB, color: BRAND.white,
      });
      y -= 32;
    };

    const drawText = (text: string, opts: {
      x?: number; size?: number; bold?: boolean; color?: typeof BRAND.text;
      maxWidth?: number; lineSpacing?: number;
    } = {}) => {
      const { x = ML, size = 10, bold = false, color = BRAND.text, maxWidth = CW, lineSpacing = size + 4 } = opts;
      const font = bold ? fontB : fontR;
      const charsPerLine = Math.floor(maxWidth / (size * 0.52));
      const lines = wrapText(text, charsPerLine);
      for (const line of lines) {
        ensure(lineSpacing + 4);
        page.drawText(line, { x, y, size, font, color });
        y -= lineSpacing;
      }
    };

    // ── PAGE 1: Header + Scores ─────────────────────────────────────────────

    // Header band
    page.drawRectangle({ x: 0, y: H - 80, width: W, height: 80, color: BRAND.dark });
    page.drawText("SIGNAL", { x: ML, y: H - 32, size: 24, font: fontB, color: BRAND.accent });
    page.drawText("Market Validation Report", { x: ML, y: H - 54, size: 12, font: fontR, color: BRAND.white });
    page.drawText(new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }), {
      x: W - MR - 120, y: H - 54, size: 10, font: fontR, color: BRAND.gray,
    });
    y = H - 100;

    // Idea title
    const titleLines = wrapText(report.ideaTitle || report.ideaDescription || "Validation Report", 55);
    page.drawText(titleLines[0], { x: ML, y, size: 16, font: fontB, color: BRAND.text });
    y -= 22;
    if (titleLines[1]) {
      page.drawText(titleLines[1], { x: ML, y, size: 16, font: fontB, color: BRAND.text });
      y -= 22;
    }
    y -= 8;

    // Score boxes: 4 across
    const scores = [
      { label: "Demand Score", value: String(report.overallScore ?? "—"), sub: "/100" },
      { label: "Founder Signal", value: String(report.founderSignal?.score ?? "—"), sub: "/100" },
      { label: "VC Signal", value: String(report.investorSignal?.score ?? "—"), sub: "/100" },
      { label: "Attention Score", value: String(Math.round((report.attentionScore?.overall ?? 0) * 10)), sub: "/100" },
    ];
    const boxW = (CW - 15) / 4;
    for (let i = 0; i < 4; i++) {
      const bx = ML + i * (boxW + 5);
      page.drawRectangle({ x: bx, y: y - 62, width: boxW, height: 62, color: BRAND.lightGray });
      page.drawText(scores[i].label, { x: bx + 6, y: y - 16, size: 8, font: fontR, color: BRAND.gray });
      page.drawText(scores[i].value, { x: bx + 6, y: y - 38, size: 22, font: fontB, color: BRAND.accent });
      page.drawText(scores[i].sub, { x: bx + 6 + (scores[i].value.length * 13), y: y - 34, size: 10, font: fontR, color: BRAND.gray });
    }
    y -= 72;

    // Verdict badge
    const verdict = report.rawVerdict || (
      (report.overallScore ?? 0) >= 70 ? "BUILD" :
      (report.overallScore ?? 0) >= 40 ? "MAYBE" : "SKIP"
    );
    const vColor = verdict === "BUILD" ? BRAND.success : verdict === "SKIP" ? BRAND.danger : BRAND.warn;
    page.drawRectangle({ x: ML, y: y - 28, width: 80, height: 28, color: vColor });
    page.drawText(verdict, { x: ML + 12, y: y - 18, size: 14, font: fontB, color: BRAND.white });
    const recLines = wrapText(report.recommendation || report.verdict || "", 62);
    page.drawText(recLines[0] || "", { x: ML + 90, y: y - 10, size: 10, font: fontR, color: BRAND.text });
    if (recLines[1]) page.drawText(recLines[1], { x: ML + 90, y: y - 22, size: 10, font: fontR, color: BRAND.text });
    y -= 40;

    // Confidence + Coverage
    if (report.confidenceScore) {
      drawText(`Confidence: ${report.confidenceScore.score ?? "—"}/100  |  ${report.confidenceScore.reasoning || ""}`, { size: 9, color: BRAND.gray });
    }
    if (report.dataCoverage) {
      const dc = report.dataCoverage;
      drawText(`Data Coverage: ${dc.totalItems} items across ${dc.successfulSources}/${dc.totalSources} sources`, { size: 9, color: BRAND.gray });
    }
    y -= 4;

    // ── Sentiment ─────────────────────────────────────────────────────────
    if (report.sentimentAnalysis) {
      drawSection("Sentiment Analysis");
      const sa = report.sentimentAnalysis;
      const sentItems = [
        { label: "Positive", value: sa.positive ?? 0, color: BRAND.success },
        { label: "Neutral", value: sa.neutral ?? 0, color: BRAND.warn },
        { label: "Negative", value: sa.negative ?? 0, color: BRAND.danger },
      ];
      let sx = ML;
      for (const s of sentItems) {
        const bw = Math.round(CW * (s.value / 100)) - 4;
        if (bw > 0) {
          page.drawRectangle({ x: sx, y: y - 22, width: bw, height: 22, color: s.color });
          if (bw > 35) page.drawText(`${s.label} ${s.value}%`, { x: sx + 4, y: y - 14, size: 8, font: fontR, color: BRAND.white });
          sx += bw + 4;
        }
      }
      y -= 32;
      if (sa.trendDirection) drawText(`Trend: ${sa.trendDirection}`, { size: 9, color: BRAND.gray });
    }

    // ── PAGE 2: Competitors + Revenue ─────────────────────────────────────

    if (report.competitorMap?.length) {
      drawSection("Competitive Landscape");
      // Table header
      page.drawRectangle({ x: ML, y: y - 18, width: CW, height: 18, color: BRAND.lightGray });
      page.drawText("Company", { x: ML + 4, y: y - 12, size: 8, font: fontB, color: BRAND.text });
      page.drawText("Description", { x: ML + 130, y: y - 12, size: 8, font: fontB, color: BRAND.text });
      page.drawText("Traction", { x: ML + 350, y: y - 12, size: 8, font: fontB, color: BRAND.text });
      page.drawText("Weakness", { x: ML + 420, y: y - 12, size: 8, font: fontB, color: BRAND.text });
      y -= 22;

      for (const comp of (report.competitorMap as any[]).slice(0, 8)) {
        ensure(22);
        page.drawText(String(comp.name || "").slice(0, 18), { x: ML + 4, y: y - 10, size: 8, font: fontR, color: BRAND.text });
        page.drawText(String(comp.description || "").slice(0, 30), { x: ML + 130, y: y - 10, size: 8, font: fontR, color: BRAND.text });
        page.drawText(String(comp.estimatedTraction || "").slice(0, 10), { x: ML + 350, y: y - 10, size: 8, font: fontR, color: BRAND.gray });
        page.drawText(String(comp.biggestWeakness || "").slice(0, 20), { x: ML + 420, y: y - 10, size: 8, font: fontR, color: BRAND.danger });
        y -= 16;
      }
      y -= 8;
    }

    if (report.revenueModel) {
      drawSection("Revenue Model");
      const rm = report.revenueModel;
      drawText(`Suggested Model: ${rm.suggestedModel || "—"}`, { bold: true });
      drawText(`Price Sensitivity: ${rm.priceSensitivity || "—"}  |  Estimated Range: ${rm.estimatedPriceRange || "—"}`, { size: 9, color: BRAND.gray });
      if (rm.proofQuotes?.length) {
        for (const q of (rm.proofQuotes as string[]).slice(0, 2)) {
          drawText(`"${q}"`, { size: 9, color: BRAND.accent, maxWidth: CW - 10 });
        }
      }
      y -= 4;
    }

    // ── Target Personas ───────────────────────────────────────────────────
    if (report.targetPersonas?.length) {
      drawSection("Target Personas");
      for (const p of (report.targetPersonas as any[]).slice(0, 3)) {
        ensure(50);
        page.drawRectangle({ x: ML, y: y - 44, width: CW, height: 44, color: BRAND.lightGray });
        page.drawText(String(p.role || "Unknown Role"), { x: ML + 8, y: y - 14, size: 10, font: fontB, color: BRAND.accent });
        const painLines = wrapText(String(p.primaryPainPoint || ""), 70);
        page.drawText(painLines[0] || "", { x: ML + 8, y: y - 27, size: 9, font: fontR, color: BRAND.text });
        if (p.representativeQuote) {
          const ql = wrapText(String(p.representativeQuote).slice(0, 90), 70);
          page.drawText(`"${ql[0]}"`, { x: ML + 8, y: y - 40, size: 8, font: fontR, color: BRAND.gray });
        }
        y -= 52;
      }
    }

    // ── Build Recommendations ─────────────────────────────────────────────
    if (report.buildRecommendations) {
      drawSection("Build Recommendations");
      const br = report.buildRecommendations;
      if (br.targetAudience) drawText(`Target: ${br.targetAudience}`, { bold: true });
      if (br.topFeatures?.length) {
        drawText("Top Features:", { bold: true, size: 9 });
        for (const f of (br.topFeatures as string[]).slice(0, 5)) {
          drawText(`  • ${f}`, { size: 9, color: BRAND.text });
        }
      }
      if (br.bestChannels?.length) {
        drawText(`Best Channels: ${(br.bestChannels as string[]).join(", ")}`, { size: 9, color: BRAND.gray });
      }
      if (br.biggestRisk) drawText(`Risk: ${br.biggestRisk}`, { size: 9, color: BRAND.danger });
      y -= 4;
    }

    // ── Next Steps ────────────────────────────────────────────────────────
    if (report.nextSteps?.length) {
      drawSection("Next Steps");
      for (const step of (report.nextSteps as any[]).slice(0, 5)) {
        const detail = typeof step === "string" ? step : step.detail || step.title || "";
        drawText(`${step.emoji || "→"}  ${String(detail).slice(0, 100)}`, { size: 9 });
      }
      y -= 4;
    }

    // ── Proof Quotes ──────────────────────────────────────────────────────
    if (report.quotes?.length) {
      drawSection("Top Proof Quotes");
      for (const q of (report.quotes as any[]).slice(0, 10)) {
        ensure(48);
        page.drawRectangle({ x: ML, y: y - 42, width: 3, height: 42, color: BRAND.accent });
        const qLines = wrapText(`"${q.text || ""}"`, 72);
        page.drawText(qLines[0] || "", { x: ML + 10, y: y - 12, size: 9, font: fontR, color: BRAND.text });
        if (qLines[1]) page.drawText(qLines[1], { x: ML + 10, y: y - 24, size: 9, font: fontR, color: BRAND.text });
        page.drawText(`${q.platform || ""}${q.upvotes ? ` · ${q.upvotes} upvotes` : ""}`, {
          x: ML + 10, y: y - 36, size: 8, font: fontR, color: BRAND.gray,
        });
        y -= 50;
      }
    }

    // Footer on last page
    drawFooter(page);

    const pdfBytes = await doc.save();

    return new Response(pdfBytes, {
      headers: {
        ...corsHeaders,
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="signal-report-${Date.now()}.pdf"`,
      },
    });
  } catch (e) {
    console.error("generate-pdf error:", e);
    return new Response(JSON.stringify({ error: String(e) }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
